export const SET_USERS_PENDING = 'SET_USERS_PENDING'
export const SET_USERS_ERROR = 'SET_USERS_ERROR'
export const SET_USERS_SUCCESS = 'SET_USERS_SUCCESS'

export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS'
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR'
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'
export const CLEAR_USER_STATE = 'CLEAR_USER_STATE'

export const ADD_USER = 'ADD_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const REMOVE_USER = 'REMOVE_USER'

export const SET_ITEMS_PENDING = 'SET_ITEMS_PENDING'
export const SET_ITEMS_ERROR = 'SET_ITEMS_ERROR'
export const SET_ITEMS_SUCCESS = 'SET_ITEMS_SUCCESS'

export const SET_CURRENT_ITEM_SUCCESS = 'SET_CURRENT_ITEM_SUCCESS'
export const SET_CURRENT_ITEM_ERROR = 'SET_CURRENT_ITEM_ERROR'
export const CLEAR_CURRENT_ITEM = 'CLEAR_CURRENT_ITEM'
export const CLEAR_ITEM_STATE = 'CLEAR_ITEM_STATE'

export const ADD_ITEM = 'ADD_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'

export const ADD_ITEM_TO_BASKET = 'ADD_ITEM_TO_BASKET'
export const UPDATE_ITEM_IN_BASKET = 'UPDATE_ITEM_IN_BASKET'
export const REMOVE_ITEM_FROM_BASKET = 'REMOVE_ITEM_FROM_BASKET'
export const CLEAR_BASKET_STATE = 'CLEAR_BASKET_STATE'


export const SET_ORDERS_PENDING = 'SET_ORDERS_PENDING'
export const SET_ORDERS_ERROR = 'SET_ORDERS_ERROR'
export const SET_ORDERS_SUCCESS = 'SET_ORDERS_SUCCESS'

export const SET_CURRENT_ORDER_SUCCESS = 'SET_CURRENT_ORDER_SUCCESS'
export const SET_CURRENT_ORDER_ERROR = 'SET_CURRENT_ORDER_ERROR'
export const CLEAR_CURRENT_ORDER = 'CLEAR_CURRENT_ORDER'
export const CLEAR_ORDER_STATE = 'CLEAR_ORDER_STATE'

export const ADD_ORDER = 'ADD_ORDER'
export const UPDATE_ORDER = 'UPDATE_ORDER'
export const REMOVE_ORDER = 'REMOVE_ORDER'


