export const SET_USERS_PENDING = 'SET_USERS_PENDING'
export const SET_USERS_ERROR = 'SET_USERS_ERROR'
export const SET_USERS_SUCCESS = 'SET_USERS_SUCCESS'

export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS'
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR'
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'

export const ADD_USER = 'ADD_USER'