export const SET_USERS_PENDING = 'SET_USERS_PENDING'
export const SET_USERS_ERROR = 'SET_USERS_ERROR'
export const SET_USERS_SUCCESS = 'SET_USERS_SUCCESS'

export const SET_CURRENT_USER_SUCCESS = 'SET_CURRENT_USER_SUCCESS'
export const SET_CURRENT_USER_ERROR = 'SET_CURRENT_USER_ERROR'
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER'

export const ADD_USER = 'ADD_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const REMOVE_USER = 'REMOVE_USER'

export const SET_ITEMS_PENDING = 'SET_ITEMS_PENDING'
export const SET_ITEMS_ERROR = 'SET_ITEMS_ERROR'
export const SET_ITEMS_SUCCESS = 'SET_ITEMS_SUCCESS'

export const SET_CURRENT_ITEM_SUCCESS = 'SET_CURRENT_ITEM_SUCCESS'
export const SET_CURRENT_ITEM_ERROR = 'SET_CURRENT_ITEM_ERROR'
export const CLEAR_CURRENT_ITEM = 'CLEAR_CURRENT_ITEM'

export const ADD_ITEM = 'ADD_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'
